### ISSUE TITLE
Consider adopting SemVer

### ISSUE THREAD

**Issue by latortuga** [jpmcgrath/shortener#103]
I understand that technically this project complies with SemVer because it is pre 1.0, but introducing breaking changes on minor releases is really bad form. Please consider bumping to a 1.0 release and following SemVer.

**Comment by jpmcgrath** [comment]
@latortuga thanks for your feedback. It would be helpful if you could point to the specific version/change in functionality? I do not know of any breaking changes that were added recently, and our intention is to follow semantic versioning going forward.

**Comment by latortuga** [comment]
Referring specifically to [this](https://github.com/jpmcgrath/shortener#v056-to-v061), we upgraded our bundle from 0.5.5 to 0.8.0 and generating a short URL stopped working. Started working again when we added and ran the migration. A required schema change that breaks the core functionality if you don't do it seems to fit the bill for major version bump.

And BTW, neither 0.5.6 nor 0.6.1 exist in the Github tags. Further, the README refers to 0.5.1 and 0.5.2, neither of which exist in the Github tags either.

**Comment by jpmcgrath** [comment]
Ok, thanks for that extra information. That makes more sense. v0.5.5 was released November 2015, and at that time we (I) was not adhering to the tenets of semantic versioning for this gem. I agree that was a change that warranted bumping the major version number, and if we were to release such a change today we would bump the major version number, or make the change in a backwards compatible way.

I think that the suggestion to release at version 1 and include notes on versioning strategy in the README is a good one. And thanks for noting that those tags are missing from the repo - i will add them when I get some time.

Can I now give you a piece of advice? This project, and many others that you are probably using for free are the result of volunteer labor. We work on this project because we enjoy it and want to share with the community. You and I are effectively strangers to one another, with our relationship beginning with you receiving a gift of code from myself and other contributors to the project. With this in mind I feel that your comment describing part of our efforts as "really bad form" to be impolite and inappropriate. Now I know that the written word is imprecise, and I doubt that your aim was to cause offense, so I can move past this. However I encourage you to choose your words more carefully in the future when communicating requests with providers of open source software, and to consider throwing out some words of appreciation when starting these conversations.
