### ISSUE TITLE
New release? (Rails 6 deprecation warning)

### ISSUE THREAD

**Issue by 97jaz** [jpmcgrath/shortener#117]
The Rails 6 release candidate gives a deprecation warning for the use of `exists?` in `app/models/shortener/shortened_url.rb:134:in `generate_unique_key'`. It says:

> DEPRECATION WARNING: Class level methods will no longer inherit scoping from `create` in Rails 6.1. To continue using the scoped relation, pass it into the block directly. To instead access the full set of models, as Rails 6.1 will, use `Shortener::ShortenedUrl.unscoped`.

But it looks like this was [already updated](https://github.com/jpmcgrath/shortener/commit/bb9001447d21e74b8248deb1010cf37c8280d417#diff-2d34f1c6ac3aef84f8d19ed465268c9dR137) in the development branch. 

Will there be a new release soon?

**Comment by FlorianDoublet** [comment]
+1

**Comment by 97jaz** [comment]
Do any of the maintainers have a position on this?

**Comment by craigmcnamara** [comment]
Thanks for the report. I'm no longer an active user, but I do still help land pull requests since I was graciously given commit rights. If you'd like to send a pull request I'll promptly review it and merge if I don't see any issues, but 👍 or +1s don't motivate me to investigate bugs. I usually investigate bugs and send pull requests on projects that I use as a way of helping keep things going and sharing the maintenance burden of projects I like.

If you've looking for a good first open source contribution, this is a golden opportunity.

**Comment by 97jaz** [comment]
As I mentioned in the description, it appears that this issue was fixed a long time ago in the `develop` branch. This is why I never bothered to submit a PR; the work _was already done_ and was just awaiting someone to cut a new release, or so it seemed.

What puzzles me even more is that you have been merging code into the `develop` branch, though this is not the branch that represents the released version of the gem (which would be the `master` branch). That makes me think that, in your eyes, the `develop` branch is the "official" one. If that's the case, can you just cut a new release of the gem off of that branch?

Again, there is no need for a PR here. The work is already done.
