### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by ajsharp** [jpmcgrath/shortener#139]
Hi. Thanks for all your work on this project. I'm wondering if there are breaking changes between the 0.8.x branch and 5.x. Thanks.

**Comment by jpmcgrath** [comment]
Hey @ajsharp, my philosophy is to avoid breaking changes where possible, and I cannot point to any breaking changes that I know of. If we knew of any, they would be noted in the README. That said, it has been over 6 years since the release of the the v0.5.x (and mistagged 5.x) releases, so I can give no guarantees.

I have looked at a diff between current develop branch and v0.5.3, and cannot see any thing of note. Can I suggest that you also have a look (it's really not a lot of changes) and see if you note anything.

https://github.com/jpmcgrath/shortener/compare/v0.5.3...develop

Good practice would be to write some specs that verify the important behavior of your dependencies, and then you can upgrade with more confidence.

Good luck!
