### ISSUE TITLE
Bad 301 Redirect

### ISSUE THREAD

**Issue by zachrnolan** [jpmcgrath/shortener#36]
My shortened url does bring me to the correct page (ex: onyxla.co/qfohu). However, I'm having issues with it working properly when sharing on Facebook.

Using Facebook's Open Graph Object Debugger, it gives me this error:

![object_debugger](https://cloud.githubusercontent.com/assets/66614/6738742/3c1adf34-ce31-11e4-80f7-53c83fb3ce82.png)

Notice that the URL shortener seems to be adding in a "http:/" in the middle of the URL causing Facebook to receive a 404 error for that URL.

Please let me know if this is not an issue with the gem and I can remove this issue.

Thanks!

**Comment by jpmcgrath** [comment]
@zachrnolan I think this is happening because you are passing in a relative path URL into the shortener, rather than a fully qualified url. This feature is not yet supported, so to work around this issue, pass in a full url into the generator.

I think this is a use case that the gem should support, so I will aim to implement it soon.

**Comment by jpmcgrath** [comment]
The behaviour just released in v0.5.0 addresses this issue. Now when URL without a protocol is passed the the generator, Shortener assumes that it is a relative path. Please see the readme for more information.

**Comment by zachrnolan** [comment]
Thanks @jpmcgrath! I'll upgrade and let you know how it goes.
