### ISSUE TITLE
unknown attribute 'expires_at' for Shortener::ShortenedUrl.

### ISSUE THREAD

**Issue by ManuelFrigerio** [jpmcgrath/shortener#45]
Hi, 

all of the sudden this gem is creating me problems.

This is the log message:

    unknown attribute 'expires_at' for Shortener::ShortenedUrl.

Any help?

**Comment by jpmcgrath** [comment]
Hi @ManuelFrigerio, this would be because of a new column that was added recently to the gem. You must have upgraded, and a migration will need to be run. If you look at the following migration from the specs dummy app:

https://github.com/jpmcgrath/shortener/blob/develop/spec/dummy/db/migrate/20150919033108_add_expires_at_to_shortened_url.rb

At the same time you might want to add the following migration:

https://github.com/jpmcgrath/shortener/blob/develop/spec/dummy/db/migrate/20150919033038_change_url_field_to_text_on_shortened_url.rb

This will allow you to store URLs longer than the previous versions string column.

**Comment by jpmcgrath** [comment]
I'll also make a note in the readme to ensure that others don't get caught out by this.

**Comment by ManuelFrigerio** [comment]
Hi @jpmcgrath , thanks for getting back to me!

So, summarising:
- I add the 2 files
- Run the migration

Done

**Comment by jpmcgrath** [comment]
Correct. You'll probably want to generate the migrations with a
   rails g migration add_expires_at_to_shortened_rul
Then copy and paste the content of that migration in there (making sure the`def change` lines are uncommented. Do something similar for the other migration.

Cheers..
